# Generated by Django 5.2.4 on 2025-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
    ]
