# Generated by Django 5.2.4 on 2025-08-11 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the user', max_length=200)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Input MSE', 'Input MSE'), ('Production MSE', 'Production MSE'), ('Output MSE', 'Output MSE')], help_text="User's role in the system", max_length=20)),
                ('mse_type', models.CharField(blank=True, help_text='Type of MSE if applicable', max_length=50)),
                ('mse_code', models.CharField(blank=True, help_text='MSE code if applicable', max_length=50)),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('company', models.CharField(blank=True, help_text="User's company name", max_length=200)),
                ('location', models.CharField(blank=True, help_text="User's location", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the user', max_length=200)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('phone', models.CharField(help_text="User's phone number", max_length=20)),
                ('company', models.CharField(help_text="User's company name", max_length=200)),
                ('mse_type', models.CharField(choices=[('Input MSE', 'Input MSE'), ('Production MSE', 'Production MSE'), ('Output MSE', 'Output MSE')], help_text='Type of MSE', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Registration status', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('branch_id', models.CharField(blank=True, help_text='Branch identifier', max_length=100)),
                ('group_id', models.CharField(blank=True, help_text='Group identifier', max_length=100)),
                ('cause', models.TextField(blank=True, help_text='Reason for registration')),
                ('nationality', models.CharField(blank=True, help_text="User's nationality", max_length=100)),
                ('send_sms', models.BooleanField(default=False, help_text='Whether to send SMS notifications')),
                ('subscribe', models.BooleanField(default=False, help_text='Whether to subscribe to updates')),
                ('company_id', models.CharField(blank=True, help_text='Company identifier', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending User',
                'verbose_name_plural': 'Pending Users',
                'ordering': ['-registration_date'],
            },
        ),
    ]
