# Generated by Django 5.2.4 on 2025-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ussd_enabled',
            field=models.BooleanField(default=False, help_text='Allow USSD access for this user'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ussd_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed PIN for USSD authentication', max_length=255),
        ),
    ]
