# Generated by Django 5.2.4 on 2025-08-22 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_ussd_enabled_customuser_ussd_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 070, 074, 075, +2567, or 2567 and be 10–13 digits long.', regex='^(?:\\+256|256|0)(7[045])\\d{7}$')]),
        ),
    ]
