# Generated by Django 4.2.10 on 2025-09-04 18:50

from django.db import migrations, models
import django.db.models.deletion
import decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('mse', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Add any missing fields for markets app
        # This is a placeholder migration that can be expanded as needed
    ]
