# Generated by Django 4.2.10 on 2025-09-04 18:50

from django.db import migrations, models
import django.db.models.deletion
import decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Add missing fields to MSE model
        migrations.AddField(
            model_name='mse',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to manage this MSE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mses', to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='mse',
            name='first_name',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='last_name',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='nin',
            field=models.CharField(max_length=20, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='phone',
            field=models.CharField(max_length=20, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='email',
            field=models.EmailField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mse_profiles/'),
        ),
        migrations.AddField(
            model_name='mse',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mses', to='mse.msecategory'),
        ),
        migrations.AddField(
            model_name='mse',
            name='location',
            field=models.CharField(blank=True, max_length=255, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='business_name',
            field=models.CharField(blank=True, help_text='Official business name', max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of business', max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mse',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mses', to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='mse',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mse',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
