# Generated by Django 4.2.10 on 2025-09-04 20:00

from django.db import migrations, models
import django.db.models.deletion
import decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0002_auto_20250904_1850'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Add only the missing assigned_agent field
        migrations.AddField(
            model_name='mse',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to manage this MSE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mses', to='authentication.customuser'),
        ),
        # Add missing business-related fields
        migrations.AddField(
            model_name='mse',
            name='business_name',
            field=models.CharField(blank=True, help_text='Official business name', max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of business', max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='mse',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mses', to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='mse',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mse',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
