# Generated by Django 4.2.10 on 2025-09-02 13:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='mse.mse')),
            ],
            options={
                'unique_together': {('mse', 'product_name')},
            },
        ),
    ]
