# Generated by Django 5.2.4 on 2025-08-16 05:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trend', models.CharField(max_length=255)),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Trend',
                'verbose_name_plural': 'Market Trends',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['impact'], name='reports_mar_impact_c99ef4_idx'), models.Index(fields=['region'], name='reports_mar_region_fdcce9_idx'), models.Index(fields=['confidence'], name='reports_mar_confide_e755e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=20)),
                ('prediction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-prediction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'metric'], name='reports_pre_user_id_640c9a_idx'), models.Index(fields=['prediction_date'], name='reports_pre_predict_ffb197_idx'), models.Index(fields=['trend'], name='reports_pre_trend_4a6c05_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sales', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'product_name'], name='reports_pro_user_id_d0fdab_idx'), models.Index(fields=['category'], name='reports_pro_categor_f583c0_idx'), models.Index(fields=['period'], name='reports_pro_period_6ef6e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orders', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='reports_sal_user_id_7c2f01_idx'), models.Index(fields=['date'], name='reports_sal_date_5ea579_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
