# Generated by Django 4.2.10 on 2025-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rights',
            field=models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('export', 'Export')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('mse', 'MSE'), ('partner', 'Partner')], max_length=10),
        ),
    ]
