# Generated by Django 4.2.10 on 2025-09-04 18:50

from django.db import migrations, models
import django.db.models.deletion
import decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction'),
        ('mse', '0001_initial'),
        ('loans', '0001_initial'),
        ('markets', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Add new fields to WalletTransaction
        migrations.AddField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=15, default=decimal.Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=15, default=decimal.Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='loans.grouploan'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='markets.transaction'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Rename reference to reference_number
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='reference',
            new_name='reference_number',
        ),
        
        # Update transaction type choices
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('payment', 'Payment'), ('refund', 'Refund'), ('fee', 'Fee'), ('adjustment', 'Balance Adjustment')], max_length=25),
        ),
    ]
