# Generated by Django 5.2.4 on 2025-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputMSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_categories', models.JSONField(default=list, help_text='Categories of inputs sourced')),
                ('supplier_network_size', models.IntegerField(default=0, help_text='Number of suppliers in network')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('lead_time_days', models.IntegerField(default=0, help_text='Average lead time in days')),
                ('quality_standards', models.TextField(blank=True, help_text='Quality standards maintained')),
                ('storage_capacity', models.CharField(blank=True, help_text='Storage capacity description', max_length=100)),
                ('primary_inputs', models.JSONField(default=list, help_text='List of primary inputs sourced')),
                ('seasonal_inputs', models.JSONField(default=list, help_text='Seasonal inputs and their periods')),
                ('input_costs_tracking', models.BooleanField(default=True, help_text='Track input costs separately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_mse', to='mses.mse')),
            ],
            options={
                'verbose_name': 'Input MSE',
                'verbose_name_plural': 'Input MSEs',
            },
        ),
        migrations.CreateModel(
            name='MSECategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_category', models.CharField(choices=[('input', 'Input MSE'), ('output', 'Output MSE'), ('production', 'Production MSE'), ('hybrid', 'Hybrid MSE')], max_length=20)),
                ('secondary_categories', models.JSONField(default=list, help_text='Secondary categories if hybrid')),
                ('category_description', models.TextField(blank=True, help_text='Description of business category')),
                ('category_performance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mses.mse')),
            ],
            options={
                'verbose_name': 'MSE Category',
                'verbose_name_plural': 'MSE Categories',
            },
        ),
        migrations.CreateModel(
            name='OutputMSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_categories', models.JSONField(default=list, help_text='Categories of outputs sold')),
                ('customer_network_size', models.IntegerField(default=0, help_text='Number of customers in network')),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sales_channels', models.JSONField(default=list, help_text='Sales channels used')),
                ('marketing_strategy', models.TextField(blank=True, help_text='Marketing strategy description')),
                ('primary_products', models.JSONField(default=list, help_text='List of primary products/services')),
                ('seasonal_products', models.JSONField(default=list, help_text='Seasonal products and their periods')),
                ('pricing_strategy', models.CharField(blank=True, help_text='Pricing strategy used', max_length=100)),
                ('delivery_methods', models.JSONField(default=list, help_text='Delivery methods offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_mse', to='mses.mse')),
            ],
            options={
                'verbose_name': 'Output MSE',
                'verbose_name_plural': 'Output MSEs',
            },
        ),
        migrations.CreateModel(
            name='ProductionMSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_capacity', models.CharField(blank=True, help_text='Production capacity description', max_length=100)),
                ('production_process', models.TextField(blank=True, help_text='Production process description')),
                ('equipment_list', models.JSONField(default=list, help_text='List of production equipment')),
                ('quality_control', models.TextField(blank=True, help_text='Quality control procedures')),
                ('raw_materials_required', models.JSONField(default=list, help_text='Raw materials required for production')),
                ('production_cycle_time', models.CharField(blank=True, help_text='Production cycle time', max_length=50)),
                ('waste_management', models.TextField(blank=True, help_text='Waste management procedures')),
                ('safety_protocols', models.TextField(blank=True, help_text='Safety protocols')),
                ('daily_production_target', models.IntegerField(default=0, help_text='Daily production target')),
                ('efficiency_metrics', models.JSONField(default=dict, help_text='Production efficiency metrics')),
                ('maintenance_schedule', models.TextField(blank=True, help_text='Equipment maintenance schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_mse', to='mses.mse')),
            ],
            options={
                'verbose_name': 'Production MSE',
                'verbose_name_plural': 'Production MSEs',
            },
        ),
    ]
