# Generated by Django 4.2.10 on 2025-09-04 18:50

from django.db import migrations, models
import django.db.models.deletion
import decimal
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('mse', '0001_initial'),
    ]

    operations = [
        # Rename fields in GroupLoan
        migrations.RenameField(
            model_name='grouploan',
            old_name='approved_at',
            new_name='approval_date',
        ),
        migrations.RenameField(
            model_name='grouploan',
            old_name='disbursed_at',
            new_name='disbursement_date',
        ),
        migrations.RenameField(
            model_name='grouploan',
            old_name='group',
            new_name='mse',
        ),
        migrations.RenameField(
            model_name='grouploan',
            old_name='product',
            new_name='loan_product',
        ),
        
        # Add new fields to GroupLoan
        migrations.AddField(
            model_name='grouploan',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to manage this loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loans', to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='term_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='disbursement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='total_principal_paid',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='collateral',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Update status choices
        migrations.AlterField(
            model_name='grouploan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        
        # Update amount field precision
        migrations.AlterField(
            model_name='grouploan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        
        # Make loan_product nullable
        migrations.AlterField(
            model_name='grouploan',
            name='loan_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct'),
        ),
        
        # Update LoanProduct model
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('business', 'Business Loan'), ('agriculture', 'Agricultural Loan'), ('equipment', 'Equipment Loan'), ('working_capital', 'Working Capital'), ('emergency', 'Emergency Loan')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, default=decimal.Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='term_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum term in months'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='term_max',
            field=models.PositiveIntegerField(default=60, help_text='Maximum term in months'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_credit_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='required_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Update GroupLoanRepayment
        migrations.RenameField(
            model_name='grouploanrepayment',
            old_name='repaid_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='grouploanrepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
