# Generated by Django 4.2.10 on 2025-09-03 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_access'],
            },
        ),
        migrations.CreateModel(
            name='DigitalServiceUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('digital_banking', 'Digital Banking'), ('e_commerce', 'E-Commerce'), ('digital_marketing', 'Digital Marketing'), ('financial_tools', 'Financial Tools'), ('other', 'Other')], max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('usage_frequency', models.CharField(default='monthly', max_length=50)),
                ('beneficiaries_count', models.PositiveIntegerField(default=1)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_services', to='mse.mse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age_group', models.CharField(choices=[('0-35', 'Youth (0-35)'), ('35+', 'Adult (35+)')], max_length=10)),
                ('is_refugee', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='mse.mse')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
